### ISSUE TITLE
Releasing directional binaural delay data, pre-extracted features, and original quality data

### ISSUE THREAD

**Issue by Hc-Xie** [x360dataset/x360dataset-kit#1]
Thank you so much for proposing this outstanding dataset and releasing TAL codes! 

However, I noticed that the directional binaural delay data and pre-extracted features are not available yet. Are you planning to release those data or preprocessing script for generating those data in the future?

**Comment by chqwer2** [comment]
Hi Xie,

Thank you for your attention. We’re currently finalizing the scripts and hope to release them within a week. The data will also be available shortly (I would say expected in two weeks, and I’ll do my best to expedite the process).

Best,
Hao

**Comment by Hc-Xie** [comment]
Thank you for your reply! I am looking forward to it.
